# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "🔨 Build Stage Running"
            displayName: "Build Step"

  - stage: DevDeploy
    jobs:
      - job: DevDeployJob
        steps:
          - script: echo "🚀 Deploying to Dev Environment"
            displayName: "Dev Deploy Step"

  - stage: QaDeploy
    jobs:
      - job: QaDeployJob
        steps:
          - script: echo "🧪 Deploying to QA Environment"
            displayName: "QA Deploy Step"


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


